USE [master]
GO

/****** Object:  Database [PhonebookDB]    Script Date: 26/01/2022 10:43:54 AM ******/
CREATE DATABASE [PhonebookDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PhonebookDB', FILENAME = N'C:\Users\Asus\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\PhonebookDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PhonebookDB_log', FILENAME = N'C:\Users\Asus\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\PhonebookDB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PhonebookDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PhonebookDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [PhonebookDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [PhonebookDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [PhonebookDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [PhonebookDB] SET ARITHABORT ON 
GO

ALTER DATABASE [PhonebookDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PhonebookDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PhonebookDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PhonebookDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PhonebookDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [PhonebookDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [PhonebookDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PhonebookDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [PhonebookDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PhonebookDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PhonebookDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PhonebookDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PhonebookDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PhonebookDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PhonebookDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PhonebookDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PhonebookDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PhonebookDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PhonebookDB] SET  MULTI_USER 
GO

ALTER DATABASE [PhonebookDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PhonebookDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PhonebookDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PhonebookDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PhonebookDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PhonebookDB] SET QUERY_STORE = OFF
GO

USE [PhonebookDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [PhonebookDB] SET  READ_WRITE 
GO

